import re

ncbi_id = "NP_188809.2"

seq = """MAASFSVPSMIMEEEGRFEAEVAEVQTWWSSERFKLTRRPYTARDVVALRGHLKQGYASNEMAKKL
WRTLKSHQANGTASRTFGALDPVQVTMMAKHLDTIYVSGWQCSSTHTSTNEPGPDLADYPYDTVPN
KVEHLFFAQQYHDRKQREARMSMSREERTKTPFVDYLKPIIADGDTGFGGTTATVKLCKLFVERGA
AGVHIEDQSSVTKKCGHMAGKVLVAVSEHINRLVAARLQFDVMGTETVLVARTDAVAATLIQSNID
ARDHQFILGATNPSLRGKSLSSLLAEGMTVGKNGPALQSIEDQWLGSAGLMTFSEAVVQAIKRMNL
NENEKNQRLSEWLTHARYENCLSNEQGRVLAAKLGVTDLFWDWDLPRTREGFYRFQGSVAAAVVRG
WAFAQIADIIWMETASPDLNECTQFAEGIKSKTPEVMLAYNLSPSFNWDASGMTDQQMVEFIPRIA
RLGYCWQFITLAGFHADALVVDTFAKDYARRGMLAYVERIQREERTHGVDTLAHQKWSGANYYDRY
LKTVQGGISSTAAMGKGVTEEQFKESWTRPGADGMGEGTSLVVAKSRM"""

seq = seq.replace("\n", "")

isocitrate_lyase_pattern = r"K[KR]CGH[LMQR]"

x = re.search(isocitrate_lyase_pattern, seq)

phrase = 'Isocitrate lyase ({FastaID}) contains its active site {ActiveSite} starting from {pos}th position'
print(phrase.format(FastaID = ncbi_id, ActiveSite = x.group(), pos=x.start()+1))


# K-[KR]-C-G-H-[LMQR] 
# https://prosite.expasy.org/cgi-bin/prosite/nicedoc.pl?PS00161
